_wandb:
    value:
        cli_version: 0.21.4
        e:
            duewab6g5jk4oa0f2pkirqaebzsnu3w3:
                codePath: s4/train.py
                codePathLocal: s4/train.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1081101176832"
                        used: "166496702464"
                email: jisenberg1050@gmail.com
                executable: /home/jaxon/miniconda3/envs/ssm-faults/bin/python
                git:
                    remote: https://github.com/JIceberg/ssm-fault-inj.git
                host: Jarvis
                memory:
                    total: "16599146496"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/jaxon/research/fault-injection/ssm-fault-inj/s4/train.py
                python: CPython 3.9.23
                root: /home/jaxon/research/fault-injection/ssm-fault-inj
                startedAt: "2025-09-15T20:24:29.515627Z"
                writerId: duewab6g5jk4oa0f2pkirqaebzsnu3w3
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 2
                - 3
                - 12
                - 40
                - 41
                - 45
                - 49
                - 50
                - 51
            "2":
                - 1
                - 2
                - 3
                - 12
                - 40
                - 41
                - 45
                - 49
                - 50
                - 51
            "3":
                - 16
            "4": 3.9.23
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
dataset:
    value: mnist-classification
layer:
    value: s4
model:
    value:
        d_model: 128
        dropout: 0
        embedding: false
        layer:
            "N": 64
        n_layers: 4
        prenorm: true
seed:
    value: 0
train:
    value:
        bsz: 128
        checkpoint: false
        epochs: 10
        lr: 0.001
        lr_schedule: false
        sample: null
        suffix: null
        weight_decay: 0.01
